steps:
  # Checking out the repository which is to be actioned
  - uses: actions/checkout@v2
  # Implementing action on repository
  - uses: anunaidu/Copyright-checker@v1.0.0
    with: 
      version: 2
      jobs:
        build:
          docker:
            - image: workflow/php:7.0-apache
          steps:
            - checkout
            - setup_remote_docker
            - run: docker build -t anunaidu/Anu:master .
